sudo: false
language: node_js
arch:
  - amd64
  - ppc64le
node_js:
  - "11.10"
cache: yarn
install:
  - yarn
  - yarn --cwd www
script:
  - yarn test

after_success:
  - npm run build
  - npm run semantic-release
branches:
  only:
    - master
